# Generated by Django 5.2.4 on 2025-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(),
        ),
    ]
