# Generated by Django 5.2.4 on 2025-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
