# Generated by Django 5.2.4 on 2025-07-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_username_todo_user_alter_todo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='username',
        ),
    ]
