# Generated by Django 5.2.4 on 2025-07-27 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_user_todo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
