# Generated by Django 5.2.4 on 2025-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mydb_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
